name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Job-A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, A!"
  Job-B:
    needs:
      - Job-A
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, B!"
  Job-C:
    needs:
      - Job-B
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, C!"
  Job-D:
    needs:
      - Job-B
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, C!"
  Job-E:
    needs:
      - Job-B
      - Job-A
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, C!"
  Job-F:
    needs:
      - Job-B
      - Job-A
      - Job-E
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, C!"