name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Job-A:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, A!"
  Job-B:
    needs:
      - A
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, B!"
  Job-C:
    needs:
      - B
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, C!"